import { Organization } from '../common';
import { ChatWidget } from './chat-widget';
import { Custom } from './custom';
import { Note } from './note';
import { ChatWidgetGoal } from './chat-widget-goal';
import { Message, MessagesAndEvent } from '../message';

export interface ChatMeta {
	was_proactive: boolean;
	loc_city: string;
	topic: string;
	browser_version: string;
	duration: string;
	loc_country: string;
	id: number;
	operator_created_id: number;
	data_privacy?: any;
	feedback_message: string;
	client_additional02_name: string;
	client_name: string;
	custom: Custom;
	chat_widget: ChatWidget;
	notes: Note[];
	client_email: string;
	client_additional03_value: string;
	status: string;
	client_additional02_value: string;
	messages_and_events: MessagesAndEvent[];
	loc_lon: number;
	chat_widget_goal: ChatWidgetGoal;
	visits: number;
	client_additional01_value: string;
	marked_read: boolean;
	post_survey_option: string;
	ended_at: string;
	browser_os: string;
	url: string;
	referrer?: any;
	created_at: string;
	messages: Message[];
	rate: number;
	browser_name: string;
	loc_lat: number;
	inital_url: string;
	client_additional01_name: string;
	client_additional03_name: string;
	organization: Organization;
	client_uuid: string;
	page_impressions: number;
}