import { Organization } from '../common';
import { Slot } from './slot';
import { OperatorGroup } from './operator-group';

export interface Operator {
	sound_message_first: boolean;
	last_name: string;
	is_role_admin: boolean;
	locale: string;
	sound_disconnect: boolean;
	timezone: string;
	slots: Slot;
	show_system_messages: boolean;
	id: number;
	show_navigation_messages: boolean;
	first_name: string;
	sound_message_new: boolean;
	is_role_staff: boolean;
	ishout_chat_meta_message_received: boolean;
	sound_message_received: boolean;
	sound_operator_on: boolean;
	is_role_agent: boolean;
	ishout_chat_meta_message_first: boolean;
	role: string;
	inactivity_sound: boolean;
	sound_bot_off: boolean;
	email: string;
	receive_email_offline_messages: boolean;
	username: string;
	is_locked_or_is_disabled: boolean;
	operator_group: OperatorGroup;
	timezone_offset: number;
	is_active: boolean;
	receive_email_stats: boolean;
	sound_connect: boolean;
	sound_message_sent: boolean;
	receive_email_chat_meta: boolean;
	jid: string;
	inactivity_timeout: number;
	sound_bot_on: boolean;
	url_image: string;
	lang: string;
	sound_operator_off: boolean;
	name: string;
	is_locked: boolean;
	receive_email_userlike: boolean;
	enabled: boolean;
	role_name: string;
	shortcuts_enabled: boolean;
	ishout_chat_meta_message_sent: boolean;
	organization: Organization;
	ishout_chat_meta_message_new: boolean;
}
